# Generated by Django 3.1 on 2020-08-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Service Based', 'Service Based'), ('Product based', 'Product Based'), ('Startup', 'Startup')], max_length=20)),
                ('domain', models.CharField(max_length=20)),
            ],
        ),
    ]
