# Generated by Django 3.1 on 2020-08-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desg', models.CharField(max_length=20)),
                ('ctc', models.FloatField()),
                ('exp', models.FloatField()),
                ('loc', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompanyApp.company')),
            ],
        ),
    ]
