# Generated by Django 3.1 on 2020-08-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('eaddress', models.CharField(max_length=30)),
                ('eemail', models.CharField(max_length=20)),
                ('ephone', models.IntegerField()),
            ],
        ),
    ]
