# Generated by Django 3.1 on 2020-08-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Simg',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
